server.port=${SERVER_PORT:8080}
app.base-url=${BSAE_URL:http://localhost:8080}
ratelimit.max=${RATE_LIMIT_MAX:120}
ratelimit.window-seconds=${RATE_LIMIT_WINDOW:60}

# springdoc / swagger-ui
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs

spring.web.resouces.static-locations=classpath:/static/